### PR TITLE
Support certificates with no CN in the Subject

### PR DESCRIPTION
**Pull request by robsco-git**
## Description of the changes

Support certificates with no Common Name (CN) in the Subject.

## Caveats

Assumes a Organisation Name exists in the certificate's Subject.

## Checklist

Please go over this checklist to increase the chances of your PR being worked on in a timely manner. Deviations are allowed with proper justification (see previous section).

 - [x] I have read the project's CoC and contribution guidelines.
 - [x] I understand and agree to the terms in the [Developer Certificate of Origin](https://developercertificate.org/) as applied to this contribution.
 - [x] All new code in this PR has full test coverage.

### For bug fixes

 - [x] My changes do not affect any public API or CLI semantics.
 - [x] My PR adds regression tests (i.e. tests that fail if the bug fix is _not_ applied).
 - [x] All new code in this PR has full test coverage.

### CODE REVIEW

**Comment by MatthiasValvekens** [comment]
I fixed the issue with the breaking change in `python-barcode` (see a1e4251) and took the liberty to rebase your branch so the workflows can run to completion.

**Comment by robsco-git** [comment]
Thank's for the feedback @MatthiasValvekens. Would you prefer the test in [test_signing.py](https://github.com/MatthiasValvekens/pyHanko/blob/ab5560411caf4ec6a117c089108d997f9c8d66cb/pyhanko_tests/test_signing.py) or [test_cms.py](https://github.com/MatthiasValvekens/pyHanko/blob/ab5560411caf4ec6a117c089108d997f9c8d66cb/pyhanko_tests/test_cms.py) or elsewhere?

**Comment by MatthiasValvekens** [comment]
Good question. Since the property you changed is only used in PDF signing code and doesn't affect the actual CMS generated, `test_signing.py` would probably be better. Thanks!

**Comment by MatthiasValvekens** [comment]
Oh, one somewhat important thing that I forgot to mention: that property is actually only used to generate the signature's visual appearance. That means that you need to be careful in a couple places to avoid making the process of reading back the appearance content overly complex:

 - Don't mess around with fonts, and ensure the text in the `O` field of the name is (essentially) latin1-compatible. Using OpenType fonts would require a lot more work to recover the data; pyHanko doesn't include any tools for performing text extraction.
 - Work with a template file that already includes a single prepared visual signature field (e.g. `MINIMAL_ONE_FIELD`) and don't set the field name in `PdfSignatureMetadata`. That should make pyHanko detect & use the prepared field automatically.
 - When rereading the PDF content, you should be able to find the appearance data using `ap_content = r.root['/AcroForm']['/Fields'][0]['/AP']['/N'].data`, assuming that your `PdfFileReader` is named `r`.

 Once you have all that, and assuming the `O` field in the subject name is "Acme Corp", you can simply test for `b"Acme Corp" in ap_content`.

**Comment by robsco-git** [comment]
Thanks again for the feedback. I do plan on updating this pull request but I haven't had much time recently to dedicate to it. Should hopefully be sometime next week.

**Comment by MatthiasValvekens** [comment]
Reopening this, I still care :). I'll take care of the regression test.

**Pull request merged**
