### PR TITLE
Refine algorithm policy handling

### LINKED ISSUE #242: Allow different digest_algorithm and signature_algorithm when validating CMS
**Is your feature request related to a problem? Please describe.**
Yes, id documents with nfc chips have something called the security object (sod). This sod contains some hashes of personal information and a CMS structure signing those hashes. The signature is produced by a document issuing authority of a given country so there is not much that can be done to influence the signing process.
For Lietuvas documents these digests are in fact different. (I will check other countries in the following days)

**Describe the solution you'd like**
If I understand rfc6211 correctly the requirement for the two algorithms to be identical is not too strict.
```
   digestAlgorithm  has been implicitly protected by the fact that CMS
      has only defined one digest algorithm for each hash value length.
      (The algorithm RIPEMD-160 was never standardized.)  There is also
      an unwritten convention that the same digest algorithm should be
      used both here and for the signature algorithm.  If newer digest
      algorithms are defined so that there are multiple algorithms for a
      given hash length (it is expected that the SHA-3 project will do
      so), or that parameters are defined for a specific algorithm, much
      of the implicit protection will be lost.
```
I would suggest adding a flag (on validation_context) that would allow skipping this particular check.
These are the lines in question:
```
        if (
            sig_hash_algo is not None
            and sig_hash_algo.dump() != hash_algo_obj.dump()
        ):
            raise SignatureValidationError(
```

**Describe alternatives you've considered**
Not much right now.

**Additional context**
I am describing this as a feature not a bug because the assumption that both digest algorithms will match is very reasonable.

Here is base64 of an LT document [sod](https://lapo.it/asn1js/#d4IE-TCCBPUGCSqGSIb3DQEHAqCCBOYwggTiAgEDMQ0wCwYJYIZIAWUDBAIBMIHnBgZngQgBAQGggdwEgdkwgdYCAQAwCwYJYIZIAWUDBAIBMIHDMCUCAQEEIHk11CGlPDKXQimsPu7HsTwY-t31A_r2gGurv0n-M0KzMCUCAQIEIDxhfCMzK2BCOrj2RPs-ypMm5ftmldqKnp-EUGaAuHL7MCUCAQMEIFFxhWMgBZkXJ6LjVra8qsBFmQmDKSEcYrBwHIPVUKq1MCUCAQsEIO5XHb33PX02kJV1FyYoedJytCCaOU79vTftBbY3pqfGMCUCAQ4EIL3Lkv9ozKhGgPgvkYJoRXDNBv_9oT7KlRDcouM5iVFZoIIC6TCCAuUwggKLoAMCAQICAiePMAsGByqGSM49BAEFADBDMQswCQYDVQQGEwJMVDEXMBUGA1UECgwOQURJQyB1bmRlciBNT0kxDTALBgNVBAMMBENTQ0ExDDAKBgNVBAUTAzAwNjAeFw0yMTEyMDMxMTA4MTJaFw0zMjA0MDMxMTA4MTJaMGQxCzAJBgNVBAYTAkxUMRcwFQYDVQQKDA5BRElDIHVuZGVyIE1PSTEuMCwGA1UEAwwlRG9jdW1lbnQgU2lnbmVyIENlcnRpZmljYXRlIExpdGh1YW5pYTEMMAoGA1UEBRMDMDc4MIIBKjCB6wYHKoZIzj0CATCB3wIBATAoBgcqhkjOPQEBAh0A_____________________wAAAAAAAAAAAAAAATBTBBz____________________-_______________-BBy0BQqFDASzq_VBMlZQRLC317_YuicLOUMjVf-0AxUAvXE0R5nVx_zcRbWfo7mrj2qUi8UEOQS3Dgy9a7S_fzITkLlKA8HTVsIRIjQygNYRXB0hvTdjiLX3I_tMIt_mzUN1oFoHR2RE1YGZhQB-NAIdAP__________________FqLguPA-E90pRVxcKj0CAQEDOgAE8dehH4xTSZca9jvtS_fUFNCLhx-lxqqFuSxNH3oLOwqTNpgRd8jw98RgkMBPLA5GX867cSOnNC6jejB4MCsGA1UdEAQkMCKADzIwMjExMjAyMjIwMDAwWoEPMjAyMjAzMDIyMTU5NTlaMBgGA1UdIAQRMA8wDQYLKwYBBAGChlUBAQEwHwYDVR0jBBgwFoAUnSxc6TvhgYf7so4HqIG_PrJjOrgwDgYDVR0PAQH_BAQDAgeAMAsGByqGSM49BAEFAANHADBEAiAJx4vlPIRqZ1p5FNkv7LKCJduy4VP79fJLszapOstClgIgcQ1cMSo4-njHatG2y2QD4ZglrdeLgp7o9kxQuDimXZkxgfYwgfMCAQEwSTBDMQswCQYDVQQGEwJMVDEXMBUGA1UECgwOQURJQyB1bmRlciBNT0kxDTALBgNVBAMMBENTQ0ExDDAKBgNVBAUTAzAwNgICJ48wCwYJYIZIAWUDBAIBoEgwFQYJKoZIhvcNAQkDMQgGBmeBCAEBATAvBgkqhkiG9w0BCQQxIgQgyhrowzQ09bb48wMHgfGl-4KOBA7H52RBtfDJ_ZewQpwwCgYIKoZIzj0EAwEEQDA-Ah0Ah54gj7QxgstG8as64yfSOHZwvIbKkTmRRSx69wIdANZx3JonAujp4_k0m-MpMelexWpBS5KeZNKoqXs)

### PR DESCRIPTION
**Pull request by MatthiasValvekens**
## Description of the changes

- Introduce a subclass `CMSAlgorithmUsagePolicy` of `AlgorithmUsagePolicy` for use
   with CMS validation specifically
 - Use that subclass to put in a hook to allow incongruent digest
   algorithms (fixes #242)

## Caveats

There is some minor API incompatibility, but only in internal APIs.

## Checklist

Please go over this checklist to increase the chances of your PR being worked on in a timely manner. Deviations are allowed with proper justification (see previous section).

 - [x] I have read the project's CoC and contribution guidelines.
 - [x] I understand and agree to the terms in the [Developer Certificate of Origin](https://developercertificate.org/) as applied to this contribution.
 - [x] All new code in this PR has full test coverage.

### For new features (delete if not applicable)

 - [x] I have discussed the implementation of this feature with the project maintainer(s) on the discussion forum or over email.
 - [x] I have verified that my changes do not break existing API or CLI functionality, or ensured that all breaking changes are clearly documented in this PR.
 - [x] All public API functionality in this PR is documented.

### CODE REVIEW

**Comment by peteris-zealid** [comment]
I looked at the changes. It seems like the 'proper' way to implement the feature. I cannot shake the feeling that this is an overkill for supporting functionality that was strongly discouraged in the previous spec and prohibited in the current one.

Still, this is your codebase and your rules - I can respect that. Thank you for putting in the effort. My only question is when do you sleep?

**Review by peteris-zealid — APPROVED** [review]

**Comment by MatthiasValvekens** [comment]
Thanks!

> I looked at the changes. It seems like the 'proper' way to implement the feature. I cannot shake the feeling that this is an overkill for supporting functionality that was strongly discouraged in the previous spec and prohibited in the current one.

That's fair, but either way the `AlgorithmUsagePolicy` interface might need some CMS-specific attention in the future anyway, so I don't mind the extra effort. :) I spent like an hour on this at most (plus some extra to diagnose an issue in an existing test).

FWIW, I plan to give these "policy objects" a more prominent place in the API going forward, as a way to gradually clean up the stateful mess that is `ValidationContext`... Don't want to incur too much technical debt there :).

> My only question is when do you sleep?

Having a baby in the house does strange things to one's circadian rhythm 🙃 ...

**Comment by peteris-zealid** [comment]
A small thing I noticed is that `algorithm_usage_policy` argument in function `validate_sig_integrity` is marked as optional, but in code it will always have a real value. The typing is not correct? (also see `validate_raw`)

**Comment by MatthiasValvekens** [comment]
> A small thing I noticed is that algorithm_usage_policy argument in function validate_sig_integrity is marked as optional, but in code it will always have a real value. The typing is not correct? (also see validate_raw)

This is the way it is for historical reasons; there are a couple tests that predate the addition of the algo policy parameter, for example, and I have some experimental code lying around that calls `validate_sig_integrity` directly. I'm not necessarily opposed to making it a required param, but it'd require some care to do it right.

I've applied and merged your other suggestion, though :)

**Pull request merged**
